# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95eee17cd76b7e5b2656c94c07901c5e313a5a3e021b2b2d2c03de2de9d923396ec3aab90ccbcd4cc35d322028169206bd0fbd8111bba5f7bb738f0ebcf5e659

test:
  secret_key_base: b7a7249b8cc9a861ac4c228d55183cd881d6f06e325b583d1dd50bf38a8c5fbeb69f5e67650ff924e2ff0129ecc84b180639912b8156e41a56dc6b00b1931da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
